#!/bin/bash

# description: mmt-probe
# Start the service mmt-probe
start() {
        echo  "Starting mmt-probe: "
        (while true; do 
        /usr/bin/offlineprobe -c /etc/mmt/mmt_offline.conf
        done) &     
        echo
}

# stop the service mmt-probe
stop() {
        echo "Stopping mmt-probe_offline: "
        pkill -f "offlineprobe"
        pkill -f "run_mmt_offline"
        echo
}

# restart the mmt-probe 
restart () {

        stop 
        start

}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status mmt-probe_offline
        ;;
  restart)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
exit 0
