apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkacat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkacat
  template:
    metadata:
      labels:
        app: kafkacat
    spec:
      containers:
      - name: kafkacat
        image: edenhill/kafkacat:1.6.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 60;done"]
