#1. Zookeeper

kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_SERVER_ID
          value: "1"
        - name: ZOO_SERVERS
          value: "zookeeper:2181:2181"
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-server
  labels:
    app: zookeeper
spec:
  ports:
  - name: tcp-client
    port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    app: zookeeper
  clusterIP: None

---
#2. Kafka

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: bitnami/kafka
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "true"
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_CFG_LISTENERS
          value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "INTERNAL://kafka:9092,EXTERNAL://kafka.mmt.svc.cluster.local:9093"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "EXTERNAL"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper-server:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: "mmt-reports:1:1"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
  - name: tcp-kafka-internal
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: tcp-kafka-external
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: kafka
  type: NodePort
