# 1. deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmt-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmt-probe
  template:
    metadata:
      labels:
        app: mmt-probe
    spec:
      containers:
      - name: mmt-probe
        image: ghcr.io/montimage/mmt-probe:latest
        imagePullPolicy: Always
        env:
        - name: "MMT_SEC_5G_DOS_NGAP_INITIALUEMESSAGE_MS_LIMIT"
          value: "100" #allow max 100 InitialUEMessage during 1 millisecond
        - name: "MMT_SEC_5G_DOS_HTTP2_MS_LIMIT"
          value: "80"  #allow max 80 http2 requests having method == 131 or 130, or type == 8
        args: 
        - "-ieth0"
        - "-Xprobe-id=5"
        - "-Xkafka-output.enable=true"
        - "-Xkafka-output.hostname=kafka" #you can replace "kafka" within its IP address
        - "-Xkafka-output.port=9092"
        - "-Xkafka-output.topic=mmt-reports"
        - "-Xsession-report.output-channel=kafka"
        - "-Xsecurity.enable=true"
        - "-Xsecurity.ignore-remain-flow=DPI"
        - "-Xsecurity.exclude-rules=0-89,100-1000"
        - "-Xsecurity.output-channel=stdout,kafka"

        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"        
