# 1. deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

      - name: mmt-probe
        image: ghcr.io/montimage/mmt-probe:latest
        imagePullPolicy: Always
        args: 
        - "-ieth0"
        - "-Xkafka-output.enable=true"
        - "-Xkafka-output.hostname=kafka"
        - "-Xkafka-output.port=9092"
        - "-Xkafka-output.topic=mmt-reports"
        - "-Xsession-report.output-channel=kafka"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: http-nginx
    port: 80
    targetPort: 80
    nodePort: 30011
  selector:
    app: nginx
  type: NodePort
