name: C/C++ CI

on:
  push:
    branches: [ master, project-sancus ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-from-source
      run: sudo MMT_DPI_VERSION=project-sancus MMT_PROBE_VERSION=project-sancus ./script/install-from-source.sh
